require "buildr-dependency-extensions"
require "buildr/scala"

CORE = "org.ds:satchel:jar:0.1"
SCALATRA = "org.scalatra:scalatra_2.8.1:jar:2.0.0.M3"

repositories.remote << "http://repo1.maven.org/maven2/"

desc "satchel-scalatra - asset packaging for scalatra"
define "satchel-scalatra" do

  extend PomGenerator

  project.group = "org.ds"
  project.version = 0.1
  
  manifest["Copyright"] = "Dan Simpson (C) 2011"
  manifest["Implementation-Vendor"] = "Dan Simpson"

  compile.with transitive(CORE), transitive(SCALATRA)
  run.with transitive(CORE), transitive(SCALATRA)  
      
end
