require "buildr-dependency-extensions"
require "buildr/scala"

Java.classpath << "src/resources"
repositories.remote << "http://repo1.maven.org/maven2/"
repositories.remote << "http://www.asual.com/maven/content/groups/public"

GRIZZLED = "org.clapper:grizzled-scala_2.8.1:jar:1.0.4"
YUI = "com.yahoo.platform.yui:yuicompressor:jar:2.4.6"
LESSENGINE = "com.asual.lesscss:lesscss-engine:jar:1.0.43"

desc "satchel - asset packaging for scala"
define "satchel" do

  extend PomGenerator

  project.group = "org.ds"
  project.version = 0.1
  
  manifest["Copyright"] = "Dan Simpson (C) 2011"
  manifest["Implementation-Vendor"] = "Dan Simpson"

  compile.with transitive(GRIZZLED), transitive(YUI), transitive(LESSENGINE)
  run.with transitive(GRIZZLED), transitive(YUI), transitive(LESSENGINE)
end
